### ISSUE TITLE
EPIC: PHP for Beginners

### ISSUE THREAD

**Issue by pernillasterner** [pernillasterner/php_fundamentals#1]
### Todos

- [x] The Fundamentals
- [x] Dynamic Web Applications
- [x] Notes Mini-Project
- [x] Project Organization
- [ ] Sessions and Authentication
- [ ] Refactoring Techniques
- [ ] Meet Composer
